export const ADD_CURRENT_USER = "USER/ADD_CURRENT_USER";
export const ON_USER_OUT = "USER/ON_USER_OUT";

export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const GET_ALL_ADVERTS = "APP/GET_ALL_ADVERTS";
export const SET_CURRENT_ADVERT_ID = "APP/SET_CURRENT_ADVERT_ID";
